# SPDX-FileCopyrightText: 2022 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

branches:
    - main
    - name: next
      prerelease: true

plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - - '@semantic-release/git'
      - assets:
            ['CHANGELOG.md', 'action.yaml']
        message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'
    - - '@semantic-release/github'
