version = 1
SPDX-PackageName = "reuse-lint-action"
SPDX-PackageSupplier = "Ali Sajid Imami <395482+AliSajid@users.noreply.github.com>"
SPDX-PackageDownloadLocation = "https://github.com/Imamiland/reuse-lint-action"

[[annotations]]
path = "renovate.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Ali Sajid Imami <395482+AliSajid@users.noreply.github.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [".github/workflows/**.yaml", "CODEOWNERS"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Ali Sajid Imami <395482+AliSajid@users.noreply.github.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  ".gitignore",
  ".markdownlintignore",
  ".gitleaksignore",
  ".gitattributes",
  ".markdownlint.json",
  ".secrets.baseline",
  ".cspell.json",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Ali Sajid Imami <395482+AliSajid@users.noreply.github.com>"
SPDX-License-Identifier = "CC0-1.0"


[[annotations]]
path = "REUSE.toml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Ali Sajid Imami <395482+AliSajid@users.noreply.github.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["CODE_OF_CONDUCT.md", "CONTRIBUTING.md", "SECURITY.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Ali Sajid Imami <395482+AliSajid@users.noreply.github.com>"
SPDX-License-Identifier = "MIT"
