name: "CLA Assistant Workflow"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write
jobs:
  dco_workflow:
    uses: Imamiland/.github/.github/workflow-templates/cla-assistant-template.yaml@main
    with:
      USE_DCO: true
