---
on:
  push:
    branches:
      - main
      - next

name: Release

permissions:
  contents: read

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Attest build provenance
        id: attest
        uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
        with:
          subject-path: action.yaml

      - name: Move attestation file to dist/
        run: mv ${{ steps.attest.outputs.bundle-path }} dist/attestation.jsonl

      - name: Move action file to dist/
        run: mv action.yaml dist/action.yaml

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@b1b432f13acb7768e0c8efdec416d363a57546f2 # v4.1.1
        id: semantic
        with:
          semantic_version: 24.0.0
          extra_plugins: |
            @semantic-release/exec@6
            @semantic-release/git@10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
